name: <<YOUR PIPELINE NAME CONFIG>>

trigger:
  - master
  - feature/*

pool:
  default


stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all
        steps:
       
        - task: Docker@2
          inputs:
            containerRegistry: 'bootcampapp1'
            repository: 'BootcampappDocker'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'

        