name: CICD pipeline

trigger:
  - master
  - feature/*

pool: default

stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "bootcampapp1"
              repository: "BootcampappDocker"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"

  # Continuous Deployment Process for Staging Environment
  - stage: DeployToStaging
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment:
          name: staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  inputs:
                    containerRegistry: "bootcampapp1"
                    command: "login"
                    tags: |
                      $(Build.BuildId)

                - task: CmdLine@2
                  inputs:
                    #script: 'docker pull bootcampapp1.azurecr.io/bootcampappdocker:$(Build.BuildId)'
                    script: "docker run --restart=always -d --name bootcampappdocker -p 8080:8080 -e PGHOST=$(PGHOST) -e PGUSERNAME=$(PGUSERNAME) -e PGDATABASE=$(PGDATABASE) -e PGPASSWORD=$(PGPASSWORD) -e PGPORT=$(PGPORT) -e PORT=8080 -e HOST=0.0.0.0 -e HOST_URL=$(HOST_URL) -e COOKIE_ENCRYPT_PWD=$(COOKIE_ENCRYPT_PWD) -e NODE_ENV=development -e OKTA_ORG_URL=$(OKTA_ORG_URL) -e OKTA_CLIENT_ID=$(OKTA_CLIENT_ID) -e OKTA_CLIENT_SECRET=$(OKTA_CLIENT_SECRET) bootcampapp1.azurecr.io/bootcampappdocker:$(Build.BuildId)"

                - task: Bash@3
                  inputs:
                    script: "docker rm -f  bootcampappdocker"

                - task: Bash@3
                  inputs:
                    targetType: "inline"
                    script: "docker run --restart=always -d --name bootcampappdocker -p 8080:8080 -e PGHOST=$(PGHOST) -e PGUSERNAME=$(PGUSERNAME) -e PGDATABASE=$(PGDATABASE) -e PGPASSWORD=$(PGPASSWORD) -e PGPORT=$(PGPORT)  -e HOST_URL=$(HOST_URL) -e COOKIE_ENCRYPT_PWD=$(COOKIE_ENCRYPT_PWD) -e NODE_ENV=development -e OKTA_ORG_URL=$(OKTA_ORG_URL) -e OKTA_CLIENT_ID=$(OKTA_CLIENT_ID) -e OKTA_CLIENT_SECRET=$(OKTA_CLIENT_SECRET) -e PORT=8080 -e HOST=0.0.0.0 bootcampapp1.azurecr.io/bootcampappdocker:$(Build.BuildId)"
                    failOnStderr: true

                - task: printAllVariables@1
