name: CICD pipeline

trigger:
  - master
  - feature/*

pool: default

stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "bootcampapp1"
              repository: "BootcampappDocker"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"

  # Continuous Deployment Process for Staging Environment
  - stage: DeployToStaging
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment:
          name: staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Docker@2
                  inputs:
                    containerRegistry: 'bootcampapp1'
                    command: 'login'
                    tags: |
                        $(Build.BuildId)

                - task: CmdLine@2   
                  inputs:
                    script: 'docker pull bootcampapp1.azurecr.io/bootcampappdocker:$(Build.BuildId)'
                  
                - task: printAllVariables@1

                - task: CmdLine@2
                  displayName: Stop Current Container
                  inputs:
                   script: 'docker rm -f  bootcampappdocker || true'

                - task: Bash@3
                  inputs:
                   targetType: 'inline'
                   script: 'docker run --name bootcampappdocker  bootcampapp1.azurecr.io/bootcampappdocker:$(Build.BuildId)'
                   failOnStderr: true
